### ISSUE TITLE
Build fails for archlinux

### ISSUE THREAD

**Issue by jarun** [BytePackager/packagecore#167] opened 2019-01-15 02:00 UTC
The error I see is:

```
(1/1) Updating the info directory file...
useradd: error while loading shared libraries: libaudit.so.1: cannot open shared object file: No such file or directory
Cleaning up self packagecore-96325e707a0f3b18.
packagecore-96325e707a0f3b18
packagecore-96325e707a0f3b18
###########################################################
# Failed to build package for 'archlinux'.
###########################################################
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/packager.py", line 181, in run
    imageName=build["dockerImage"])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/packager.py", line 97, in _build
    recipe.prep(container)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/pkgbuild.py", line 190, in prep
    container.execute(["useradd", "-m", "-u", str(uid), "packagecore"])
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/docker.py", line 149, in execute
    _checkedDockerCommand(["exec", self._name] + cmd)
  File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/packagecore/docker.py", line 54, in _checkedDockerCommand
    raise DockerError("Command '%s' returned %d." % (cmd, status))
packagecore.docker.DockerError: Command '['exec', 'packagecore-96325e707a0f3b18', 'useradd', '-m', '-u', '2000', 'packagecore']' returned 127.

Full logs attached.

[log.zip](https://github.com/BytePackager/packagecore/files/2757796/log.zip)


```

**Comment by dlasalle** [comment] 2019-01-15 06:59
This looks like an issue with the container. Can you post your yaml file?

**Comment by jarun** [comment] 2019-01-15 07:01
Here you go: https://github.com/jarun/nnn/blob/master/packagecore.yaml

**Comment by dlasalle** [comment] 2019-01-15 15:24
This seems to be an issue with the last build of the `base/archlinux` container. I was able to reproduce the error with it, and using the December build `2018.12.01` I was able to get a successful build:

```
  container: "base/archlinux:2018.12.01"
```
So I'd say either find a different archlinux container, or just build from the old image until the new one is fixed by them.

**Comment by jarun** [comment] 2019-01-15 15:31
No problem! I'll use the old image.

**Comment by dlasalle** [comment] 2019-01-15 15:32
Closing as its a container issue not a packagecore issue.

**Closed by dlasalle** 2019-01-15 15:32 UTC
